---
"Area: Source":
  - any: ['src/**/*']

"Area: Datapack Core":
  - any: ['data/**/*']

"Area: Datapack Crystal":
  - any: ['data-crystal/**/*', '!data-crystal/world/*']

"Area: Datapack Global":
  - any: ['custom/**/*', '!custom/world/*']

"Area: Map Crystal":
  - any: ['data-crystal/world/*']

"Area: Map Global":
  - any: ['custom/world/*']

"Area: Docker":
  - any: ['docker/**/*']
  
